---
- name: Install nginx
  apt:
    name: nginx

- name: Enable nginx
  service:
    name: nginx
    enabled: yes

- name: Configure nginx user
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^user"
    line: "user {{ host_remote_user }};"
  notify: Restart nginx

- set_fact: website_url="www.{{ base_url }}"

- name: Disable default server
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Configure base domain nginx server
  template:
    src: nginx_server.j2
    dest: /etc/nginx/sites-available/{{ base_url }}
  notify: Restart nginx

- name: Enable base domain nginx server
  file:
    src: "/etc/nginx/sites-available/{{ base_url }}"
    dest: "/etc/nginx/sites-enabled/{{ base_url }}"
    state: link
  notify: Restart nginx
