---
- name: Install nginx
  apt: name=nginx

- name: Enable nginx
  service: name=nginx enabled=yes

- name: Configure nginx user
  lineinfile: dest=/etc/nginx/nginx.conf regexp="^user" line="user {{ host_remote_user }};"
  notify: Restart nginx
