---
- name: Static website install
  hosts: static
  remote_user: "{{ host_remote_user }}"
  roles:
    - { role: debian, become: true, tags: ['debian'] }
    - { role: nginx, become: true, tags: ['nginx'] }
    - { role: npm, become: true, tags: ['npm'] }
    - { role: yarn, become: true, tags: ['yarn'] }
    - { role: static, become: true, tags: ['static'] }
    - { role: https, become: true, when: secured_server is defined and secured_server, tags: ['https'] }
