---
- name: Ansible prerequisites
  hosts: static-website
  gather_facts: False
  remote_user: "{{ host_remote_user }}"
  become: true
  tags: ['prerequisites']
  tasks:
    - name: Check if apt repo needs to be updated
      raw: ls -1 /var/cache/apt/pkgcache.bin || true
      register: apt_repo_cache

    - name: Update repos
      raw: apt-get update
      when: apt_repo_cache.stdout_lines[0] != "/var/cache/apt/pkgcache.bin"

    - name: Make sure python and deps are installed
      raw: apt-get -y install python python-apt apt-utils python-requests python-passlib

- name: Static website install
  hosts: static-website
  remote_user: "{{ host_remote_user }}"
  roles:
    - { role: debian, become: true, tags: ['debian'] }
    - { role: nginx, become: true, tags: ['nginx'] }
    - { role: npm, become: true, tags: ['npm'] }
    - { role: static-website, become: true, tags: ['static-website'] }
