---
- name: Tiny tiny RSS install
  hosts: ttrss
  remote_user: "{{ host_remote_user }}"
  roles:
    - { role: debian, become: true, tags: ['debian'] }
    - { role: docker, become: true, tags: ['docker'] }
    - { role: ttrss, become: true, tags: ['ttrss'] }
    - { role: caddy, become: true, tags: ['caddy'] }
