---
- name: Tiny tiny RSS install
  hosts: ttrss
  remote_user: "{{ host_remote_user }}"
  roles:
    - { role: debian, become: true, tags: ['debian'] }
    - { role: mysql, become: true, tags: ['mysql'] }
    - { role: fpm, become: true, tags: ['fpm'] }
    - { role: nginx, become: true, tags: ['nginx'] }
    - { role: ttrss, become: true, tags: ['ttrss'] }
