---
- name: Install PHP FPM package
  apt: name={{ item }}
  with_items:
    - php7.1-fpm

- name: Enable PHP FPM
  service: name=php7.1-fpm enabled=yes

- name: Setting up PHP FPM config
  lineinfile: dest=/etc/php/7.1/fpm/php.ini regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - { regexp: '^memory_limit', line: 'memory_limit = 512M' }
    - { regexp: '^;?date\.timezone =', line: 'date.timezone = Europe/Paris' }


- name: Setting up PHP FPM web config
  lineinfile: dest=/etc/php/7.1/fpm/pool.d/www.conf regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - { regexp: '^user =', line: 'user = {{ host_remote_user }}' }
    - { regexp: '^group =', line: 'group = {{ host_remote_user }}' }
    - { regexp: '^listen\.owner =', line: 'listen.owner = {{ host_remote_user }}' }
    - { regexp: '^listen\.group =', line: 'listen.group = {{ host_remote_user }}' }
    - { regexp: '^listen =', line: 'listen = /run/php/php7.1-fpm.sock' }
  notify: Restart FPM
