---
- name: Add NodeJS repository key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add NodeJS official repository
  apt_repository: repo="deb https://deb.nodesource.com/node_8.x stretch main" state=present

- name: Install NodeJS and NPM
  apt:
    name: nodejs
