---
- name: Set Debian repository
  copy:
    src: debian_sources.list
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root

- name: Install some usefull packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - bzip2
      - ca-certificates
      - cron
      - curl
      - git
      - iputils-ping
      - less
      - logrotate
      - man-db
      - reboot-notifier
      - rsync
      - vim
      - wget

- name: Remove useless packages
  apt:
    name: "{{ packages }}"
    purge: yes
    state: absent
  vars:
    packages:
      - at
      - nano
      - tasksel
      - tasksel-data
      - vim-tiny

- name: Add Debian Stretch "backport" repository
  apt_repository:
    repo: deb http://ftp.fr.debian.org/debian stretch-backports main
    state: present

- name: Install Certbot from "squeeze-backport"
  apt:
    default_release: stretch-backports
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - certbot
      - python3-certbot-nginx

- name: Upgrade all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: Check if a reboot is required
  register: file
  stat:
    path: /var/run/reboot-required
    get_md5: no

- name: Reboot the server
  shell: sleep 2 && /sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: file.stat.exists == true

- name: Wait for the server after reboot
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 22
    state: started
    delay: 10
    timeout: 180
  connection: local
  become: false
  when: file.stat.exists == true

- name: Clean the install
  apt:
    autoremove: yes
    autoclean: yes
