---
- name: Install some usefull packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - cron
    - curl
    - git
    - iputils-ping
    - less
    - logrotate
    - man-db
    - rsync
    - vim
    - wget

- name: Remove useless packages
  apt: name={{ item }} purge=yes state=absent
  with_items:
    - at
    - nano
    - tasksel
    - tasksel-data
    - vim-tiny

- name: Clean the install
  shell: apt-get -y autoremove --purge
