---
- name: Install apt-transport-https
  apt: name=apt-transport-https update_cache=yes

- name: Set Debian repository
  copy: src="debian_sources.list" dest="/etc/apt/sources.list" mode=0644 owner=root

- name: Upgrade all packages to the latest version
  apt: update_cache=yes upgrade=dist

- name: Check if a reboot is required
  register: file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: file.stat.exists == true

- name: Wait for the server after reboot
  wait_for:
    port: 22
    delay: 30
  become: false
  when: file.stat.exists == true
