---
- name: Install MySQL package
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python-mysqldb
      - mysql-server

- name: Enable MySQL server
  service:
    name: mysql
    enabled: yes

- name: Update MySQL root password for all root accounts
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
