---
- name: Install PHP5 packages
  apt: name={{ item }}
  with_items:
    - php5-apcu
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-readline
    - php5-tidy
  when: php_version is not defined or php_version == 5

- name: Add PHP7 repository key
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg state=present
  when: php_version is defined and php_version == 7.0

- name: Add PHP7 repository
  apt_repository: repo="deb http://packages.dotdeb.org jessie all" state=present
  when: php_version is defined and php_version == 7.0

- name: Install PHP7 packages
  apt: name={{ item }}
  with_items:
    - php7.0-apcu
    - php7.0-cli
    - php7.0-bcmath
    - php7.0-curl
    - php7.0-gd
    - php7.0-intl
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-soap
    - php7.0-xml
    - php7.0-zip
  when: php_version is defined and php_version == 7.0

- name: Set default PHP
  alternatives: name=php path=/usr/bin/{{ (php_version is defined and php_version == 7.0) | ternary('php7.0','php5') }}
